pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Build and Test') {
            steps {
                script {
                    sh 'pwd'
                    sh 'ls -alt'
                    dir('../Jenkins-app/dockerized-springboot-and-my_sql-calculate') {
                        echo '$$$$$$$'
                        sh 'pwd' 
                        sh 'ls -alt' 
                        sh 'mvn clean package'
                    }
                }
            }
        }
    }
}
