pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        
        stage('Build and Test with Maven') {
            steps {
                script {
                    sh 'pwd'
                    sh 'ls -alt'
                    dir('../Jenkins-app/dockerized-springboot-and-my_sql-calculate') {
                        echo '$$$$$$$'
                        sh 'pwd' 
                        sh 'docker --version'
                        sh 'ls -alt' 
                        sh 'mvn clean package'
                    }
                }
            }
        }

        stage('Build and Test with Node') {
            agent {
                docker {
                    image 'node:18-alpine'
                }
            }
            steps {
                script {
                    // Assuming you need to run npm commands in the Node.js container
                    
                        sh 'pwd'
                        sh 'ls -alt'
                        sh 'npm --version'
                        // Run any additional Node.js commands needed here
                    
                }
            }
        }
    }
}
